import {deleteAction, getAction, postAction, putAction} from "@/api/manage";
import {serverIp} from "@/config/config";

export const addOrEditPlant = (param) => postAction("/plant/addOrEdit", param)
export const listPlant = (param) => getAction("/plant/list", param)
export const detailPlant = (id) => getAction("/plant/detail/info/"+id, null)
export const detailPlantList = (id) => getAction("/plant/detail/plantList/"+id, null)
export const detailPlantHistory = (id) => getAction("/plant/detail/history/"+id, null)
export const deletePlant = (id) => deleteAction("/plant/delete/"+id, null)
export const editPlant = (id, param) => putAction("/plant/edit/"+id, param)
export const userLogin = (param) => postAction("/user/login", param)
export const userRegister = (param) => postAction("/user/register", param)
export const getUser = (username) => getAction("/user/username/"+username, null)
export const updateUser = (id, param) => putAction("/user/update/"+id, param)
export const listMi = (plantId) => getAction("/mi/list/"+plantId, null)
export const getMiAllInfo = (miId) => getAction("/mi/detail/"+miId, null)
export const getMiDayPowerInfo = (miId) => getAction("/mi/dayInfo/"+miId, null)
export const listAlarmMi = () => getAction("/mi/alarm/", null)
export const addMi = (param) => postAction("/mi/add", param)
export const deleteMi = (id) => deleteAction("/mi/delete/"+id, null)
export const listAlarmDtu = () => getAction("/dtu/alarm/", null)
export const listDtu = (plantId) => getAction("/dtu/list/"+plantId, null)
export const addDtu = (param) => postAction("/dtu/add", param)
export const deleteDtu = (id) => deleteAction("/dtu/delete/"+id, null)
export const listInstitute = () => getAction("/institute/list", null)
export const listInstituteUser = (id, if_institute) => getAction(`/institute/listUser/${id}?if_institute=${if_institute}`, null)
export const saveInstitute = (param) => postAction("/institute/save", param)
export const deleteInstitute = (id) => deleteAction("/institute/delete/"+id, null)
export const resetPassword = (id) => putAction("/user/resetPwd/"+id, null)
export const deleteUser = (id) => deleteAction("/user/delete/"+id, null)
export const adminUserEdit = (param) => putAction("/user/admin/edit", param)
export const adminUserRegister = (param) => postAction("/user/admin/register", param)
export const getCount = () => getAction("/plant/count", null)
export const getGenReport = (plantId, startDate, endDate) => getAction(`/plant/genReport/${plantId}?startDate=${startDate}&endDate=${endDate}`, null)
export const exportGenReport = (plantId, startDate, endDate) => window.open("http://"+serverIp+`/plant/export/genReport/${plantId}?startDate=${startDate}&endDate=${endDate}`);


